### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by omk42** [decentralized-identity/veramo#1385]
**Bug severity**
2

**Describe the bug**
My agent's open-api route fails because of `TypeError: Cannot read properties of undefined (reading 'description')`. I manually compared the `agent.availableMethods()` and `agent.getSchema().components.methods.keys()` and they look similar. Note that `veramo server` CLI command is able to fetch open-api schema for the same agent. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Agent 

```
  export const agent = createAgent<IDIDManager & IKeyManager & IDataStore & IDataStoreORM & IResolver & ICredentialPlugin>({...})
```
3. remote setup 

```
const exposedMethods = agent.availableMethods()

const schemaRouter = ApiSchemaRouter({
  basePath,
  exposedMethods,
});

const app = express();
app.use(basePath, requestAgentRouter, agentRouter);
app.use(schemaPath, requestAgentRouter, schemaRouter);
```

**Observed behaviour**
Stack trace at `basepath/open-api.json`   

```
TypeError: Cannot read properties of undefined (reading 'description')
    at getOpenApiSchema (@veramo/remote-client/src/openApi.ts:34:61)
    at node_modules/@veramo/remote-server/src/api-schema-router.ts:52:29
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)
    at next (node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/node_modules/express/lib/router/index.js:175:3)
```

**Expected behaviour**
Same as `veramo sever` CLI 

**Versions (please complete the following information):**
 - Veramo: ^6.0.0
 - veramo remote server "^5.6.0"
 - Browser chrome
 - Node v18.17.1

**Comment by mirceanis** [comment]
seems related to #1379
