### ISSUE TITLE
Error: jsonld@https://github.com/digitalcredentials/jsonld.js.git#commit=afa0062460b987bd42887b3a294cf0e0a0e5bde7: Manifest not found

### ISSUE THREAD

**Issue by theblockstalk** [decentralized-identity/veramo#1407]
**Bug severity**
4 - afecting anyone using `@veramo/credential-w3c` that uses yarn berry (v2+) as package manager

**To Reproduce**
```bash
npm init
yarn
# all good
yarn set version 4.3.1
yarn
# still all good up to here...
yarn add @veramo/credential-w3c
```

**Observed behaviour**
```bash
dev@dev-VirtualBox:~/Downloads/my-app$ yarn add @veramo/credential-w3c
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: jsonld@https://github.com/digitalcredentials/jsonld.js.git#commit=afa0062460b987bd42887b3a294cf0e0a0e5bde7: Manifest not found
    at cE.find (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:140:120099)
    at async /home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:520:11979
    at async Object.xZe (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:140:53732)
    at async B2.resolve (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:520:11940)
    at async Pd.resolve (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:141:1451)
    at async Pd.resolve (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:141:1451)
    at async /home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:210:7249
    at async Yy (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:140:53795)
    at async Z (/home/dev/.cache/node/corepack/v1/yarn/4.3.1/yarn.js:210:7231)
➤ YN0000: └ Completed in 5s 524ms
➤ YN0000: · Failed with errors in 5s 583ms
```
   
**Expected behaviour**
Package installs

**Additional context**
See https://github.com/digitalcredentials/jsonld-signatures/issues/8

**Versions (please complete the following information):**
 - Node Version 22.3.0

**Comment by theblockstalk** [comment]
Solved by adding the following to `package.json`
```json
  "resolutions": {
    "@veramo/credential-ld": "5.6.0"
  }
```

**Comment by theblockstalk** [comment]
Also can be solved with
```json
"resolutions": {
        "jsonld": "link:./node_modules/@digitalcredentials/jsonld",
    }
```

**Comment by mirceanis** [comment]
> Also can be solved with
> 
> package.json
> 
> ```json
> "resolutions": {
>         "jsonld": "link:./node_modules/@digitalcredentials/jsonld",
>     }
> ```

I was under the impression that you are already doing this

**Comment by mirceanis** [comment]
@theblockstalk thanks to your efforts I set up a [troubleshooting guide on veramo.io](https://veramo.io/docs/troubleshooting)

See https://github.com/uport-project/veramo-website/pull/147
